### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by huyphams** [luckymarmot/ThemeKit#11]
Hi team, 

Incredible work you have done, kudos to the team 👍 

ThemeKit is awesome but it would be great if we have rules for coding. It makes ThemeKit code readable and clean.

My suggestion is SwiftLint: https://github.com/realm/SwiftLint
SwiftLint quickly becomes a new standard for Swift, it makes code much cleaner and avoids many bugs came from bad conventions.

if you guys interesting in my suggestion, I would love to give a PR.

**Comment by nfgrilo** [comment]
Hi @huyphams ! Thanks for the kind words! I know *SwiftLint* and that is definitively a good idea. If you are willing to make a PR that would be welcome and much appreciated!

**Comment by nfgrilo** [comment]
Done on PR #12
