### ISSUE TITLE
Using ThemeKit introduces visual artifacts on sheet windows

### ISSUE THREAD

**Issue by LeoNatan** [luckymarmot/ThemeKit#15]
This is a great framework!

Without ThemeKit linked in the project, everything works correctly:

![notheme](https://user-images.githubusercontent.com/2270433/38762734-dd38f61e-3f97-11e8-9437-f60971ce515b.png)

However when linking ThemeKit, no matter if the light or dark themes are used, some controls exhibit visual artifacts:

![lighttheme](https://user-images.githubusercontent.com/2270433/38762753-3550fc7a-3f98-11e8-8d4a-8729d3740bb5.png)

![darktheme](https://user-images.githubusercontent.com/2270433/38762755-3882344a-3f98-11e8-9ffd-69dcbe4fb573.png)

Now sure what is causing this.

**Comment by LeoNatan** [comment]
Notice the rectangles around the disclosure buttons and the cell text fields.

**Comment by nfgrilo** [comment]
Hi @LeoNatan !

Sorry for the late response, but I was trying to reproduce the issue with [this apple sample code](https://developer.apple.com/library/content/samplecode/SourceView/Introduction/Intro.html) (which I couldn't). However, I know this happened to me in the past, and I know it is somehow related with vibrancy. If I remember correctly, at the time I was able to fix this by playing with the [`allowsVibrancy`](https://developer.apple.com/documentation/appkit/nsview/1483793-allowsvibrancy#) property of wither the views (`NSTableView`/`NSOutlineView`) and/or the subviews, but I confess I'm not 100% sure about this.

Are you able to recreate this on a minimal project and share the code so I can take a look?

Unfortunately, there some edge cases (like this), which sometimes may require a hack...

Thanks.

**Comment by LeoNatan** [comment]
Thanks for your reply.

I'll try to play around with the vibrancy settings. The problem only occurs on sheets.
If the problem still happens after disabling the vibrancy, I'll try to reproduce it in a demo project.

**Comment by nfgrilo** [comment]
Hey @LeoNatan !

Sorry for the late response, but I was able to reproduce the issue on a sample project, and provide a fix as well. Please take a look at the comment below where this is further explained!

https://github.com/luckymarmot/ThemeKit/issues/18#issuecomment-396553982

Hope it helps!

**Comment by LeoNatan** [comment]
Thanks!

With the new Dark mode, this wouldn’t be the best solution, but it’s good enough for now. I haven’t yet been able to test on Mojave to see if the issue still occurs.
