### ISSUE TITLE
Demo for Objective-C

### ISSUE THREAD

**Issue by dilmerv** [luckymarmot/ThemeKit#16]
Hi there I love your source code but I haven't been able to integrate it into my objective-c code. Is there a way you can also post a demo for objective-c ?

Thanks!

**Comment by nfgrilo** [comment]
Hi Dilmer!

Unfortunately, the demo project is built in Swift - only. I have provided some basic instructions for Objective-C on the [Usage](https://github.com/luckymarmot/ThemeKit#usage) section - can you be more specific on the issues you're facing with?

**Comment by nfgrilo** [comment]
For some reason, your pod is not up-to-date - all the errors above are Swift version related.
ThemeKit has been written in Swift 3 and migrated to Swift 4 back on ThemeKit 1.1.1.

Try to update your pods with `pod update`, then `pod install`. If that fails, you can try a [deep cleaning](https://gist.github.com/mbinna/4202236) instead.
