### ISSUE TITLE
NSComboBox scrollbar problem

### ISSUE THREAD

**Issue by rdmeyers** [luckymarmot/ThemeKit#20]
NSComboBox has a problem with the Dark Theme when the System Preferences has "Show scroll bars" set to "Always".  I tried the allowsVibrancy work-around with it and that did not work.  Any other ideas?

![image](https://user-images.githubusercontent.com/2287754/42415178-e981613e-820b-11e8-9f7f-037ee5135c74.png)

**Comment by nfgrilo** [comment]
Yes, please check the short FAQ at the end of the [README.md](https://github.com/luckymarmot/ThemeKit/blob/master/README.md) page - I have run into this issue in the past!

Please let me know if you are able to fix it!
