### ISSUE TITLE
NSToolbar on El Capitan

### ISSUE THREAD

**Issue by rdmeyers** [luckymarmot/ThemeKit#21]
The NSToolbar is not getting the Dark Theme applied to it on El Capitan.  The same code displays properly on Sierra, High Sierra, and Mohave.  Any ideas?

![image](https://user-images.githubusercontent.com/2287754/42415213-c1c2ef04-820c-11e8-9c4c-fa5d26f3baca.png)

**Comment by nfgrilo** [comment]
That's weird! You may want to try to manually theme it:

ThemeKit provides a `NSWindow` extension, you may want to play with [`window.theme()`](https://github.com/luckymarmot/ThemeKit/blob/master/Sources/NSWindow%2BThemeKit.swift#L58) to check if this helps fixing it. 

Please check the source of this method, as it may not do anything if the window was already (supposedly) themed, so you may want to (for testing purposes) set the theme to something else before calling it, just to make sure that calling this method is of any help here...

Please let me know how it goes!
