### ISSUE TITLE
App Store Rejection

### ISSUE THREAD

**Issue by rdmeyers** [luckymarmot/ThemeKit#22]
I am not sure how they test apps at Apple, but I have been unable to replicate the scenario they get when testing the Dark Mode option.  Maybe the screen shots themselves will give you some insight as to what they might be doing?  Or what I can check?  

Screenshot 1 has some strange motion looking artifacts:

![screenshot1](https://user-images.githubusercontent.com/2287754/42667103-d4b07b1c-860e-11e8-835c-499b6b9602c8.png)

Screenshot 2 has left some controls in dark mode, while making the tab control blank, etc.

![screenshot2](https://user-images.githubusercontent.com/2287754/42667118-ec418190-860e-11e8-9fff-290ded6617ff.png)

**Comment by nfgrilo** [comment]
I also don't know how they take screenshots, but if you can't reproduce this, *eventually* they can be automated. On the screenshots, it looks like it was "in the process" of changing the theme, as some controls are not even drawn, while others appear with a different appearance.

When themes are changed, ThemeKit performs an animation. Maybe the screenshot is automated and is happening during this animation?

I don't have any extra information regarding AppStore approval/rejection, so I suggest you asking them for additional details that could help in understanding the issue and/or reproduce it.

Hope this helps.

**Comment by rdmeyers** [comment]
I agree, the second screen shot does look as though the theming process ended prematurely.  This had me thinking that possibly your recursive function that themes the individual controls may have had an access violation, thus aborting the theming process entirely.

With that thinking, I changed the code from using the universal theming function "setTheme" to instead theming each window individually using "setWindowTheme".  Being that I cannot reproduce whatever bug(s) they are finding, I did not initially see any difference.  However, theming the windows individually did display a problem when "zooming" the window, namely it lost the theme entirely!  Any ideas why that would happen?

**Comment by nfgrilo** [comment]
> Any ideas why that would happen?

Not really :/

I would really recommend asking the team further details by choosing "App Rejection Clarification" on [developer.apple.com/contact](https://developer.apple.com/contact/#!/topic/select) - hopefully, they will come up with valuable information.

**Comment by nfgrilo** [comment]
> Do you see any drawback to me going straight to "makeThemeEffective" (...)?

Yes - Please don't call that method directly.
I have just released 1.2.1 which just makes the theme transition animation optional:
[`ThemeManager.animateThemeTransitions`](https://themekit.nunogrilo.com/Classes/ThemeManager.html#/s:8ThemeKit0A7ManagerC07animateA11TransitionsSbvp)

So you can just set on your code `ThemeManager.shared.animateThemeTransitions = false` and give it a try.

> If Purgatory exists, then Apple helped design it!!! ;-)

😂🤣

**Comment by rdmeyers** [comment]
I think you need to add this boolean to ThemeManager+ObjectiveC.swift as I cannot access it.

**Comment by rdmeyers** [comment]
So omitting animation may have help on 10.13, but now they see a similar issue on 10.12:

![image](https://user-images.githubusercontent.com/2287754/42737837-b1d037d6-883e-11e8-98fa-ac7beb44ad5a.png)

Is it possible I am not including some library that is needed by ThemeKit that would not be available by default in whatever environment they are testing it in?

**Comment by nfgrilo** [comment]
>  I cannot access it

Sorry - forgot to add `@objc` to property declaration. All good now.

> Is it possible I am not including some library that is needed by ThemeKit that would not be available by default in whatever environment they are testing it in?

ThemeKit has no 3rd party dependencies - however, they may have a limited environment that could affect this (somehow). I honestly don't know how they are getting those while you can have your app correctly themed...  😔

Hopefully, Apple response will add some more insights on this...

**Comment by rdmeyers** [comment]
Apple's response is they turn on the dark theme, then start playing around with the app and the theme disappears.  No real step-by-step, but it is impossible for me to reproduce even using the app archive under a limited Guest account.

**Comment by rdmeyers** [comment]
Well taking out the animation has only made the fail look cleaner :-)  This screenshot is them simply turning on the dark mode, then turning it off.  How is this even possible!!!  It looks like the tabs are completely empty as they are just pure white, whereas the comboboxes are still dark, so it seems the theming ended before it got to them.

![screenshot4](https://user-images.githubusercontent.com/2287754/42855877-2785affe-8a08-11e8-8c0c-cacb2d6bd073.png)

This screenshot is very similar to screenshot #2 above.

**Comment by nfgrilo** [comment]
I think it is really important you find a way of reproducing this on your machine. At this point, there's no way of verifying if a "fix" actually fixes it.
If this only happens on macOS 10.12, you could install this OS on *VMWare Fusion* or on *VirtualBox*, so you can attempt to reproduce it there. [Here's a script](https://github.com/geerlingguy/macos-virtualbox-vm) for helping with macOS installation on VirtualBox.

On a previous app I've worked (and used ThemeKit), there were some cases where it was necessary to listen for theme changes and make some tweaks/manual changes on some parts of the UI. These could include:

- for `NSView`s, manually setting its appearance: `view.appearance = [TKThemeManager sharedManager].effectiveThemeAppearance`
- for `NSView`s,  calling `view.needsDisplay = true` (if using custom drawing (on `drawRect:`), wiping out any cached drawings before calling this)
- if `CALayer`s were involved, calling `[layer setNeedsDisplay]`

You can listen for theme changes, either with KVO or notifications:
- `[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(_themeDidChangeNotification:) name:TKThemeManager.didChangeThemeNotification object:nil];`
- KVO on`[TKThemeManager sharedManager]`, key path "effectiveTheme"

Hope this helps.

**Comment by rdmeyers** [comment]
I cannot fix what I cannot replicate, and guessing where to put your suggestions is not fruitful either, so, unfortunately, I need to abandon theming the app for now.
