### ISSUE TITLE
How does ThemeKit cover NSColor?

### ISSUE THREAD

**Issue by DivenLee** [luckymarmot/ThemeKit#30]
Inadvertently found ThemeKit, I feel very good. But the source code may be a bit complicated for me.
Can you briefly explain how ThemeKit covers NSColor?

thx

**Comment by DivenLee** [comment]
I mainly don't understand how the system requests the ThemeColor object when it accesses NSColor. labelColor.

**Comment by nfgrilo** [comment]
Hi @DivenLee !

I would checkout the full code and take a look at the Demo project which gives some usage examples.

A couple of notes:
- The main idea is to use `ThemeColor`, `ThemeGradient` and `ThemeImage` throughout your app; these colors/gradients/images returned from these classes will dynamically change as theme changes;
- You *can* (optional) make use the override of `NSColor` named colors - that is made through [objc method swizzling](https://github.com/luckymarmot/ThemeKit/blob/master/Sources/NSColor%2BThemeKit.swift); that means that, whenever you or the system calls `NSColor.labelColor` it would be ThemeKit returning the actual colors. However, keep in mind that you can't control where these `NSColor` named colors are used through the app (you will need to check if that is changing whenver you want) - sometimes the system makes use of named colors in places we don't expect.

So, the bottom line is, although using swizzled `NSColor` named colors is cool, I would design the app using `ThemeColor` (and companion classes) whenever possible, so you have full control.

Hope this helps!
