### ISSUE TITLE
Using the library system-wide?

### ISSUE THREAD

**Issue by EclipsedVisions** [luckymarmot/ThemeKit#36]
Hello, this might sound like a stupid question, but after reading the entire documentation I still don't understand whether it is possible or not to write an app which would change the theme globally for all open applications system-wide using this library? Because I was looking to get a dark mode in High Sierra similar to the Mojave one and so far this ThemeKit has been the closest thing to what I'd need.

**Comment by nfgrilo** [comment]
Hi! Nope, ThemeKit is only for theming your own application - theming the OS is outside the scope of this library.

**Comment by preland** [comment]
Out of curiosity, is it even remotely possible for ThemeKit to be used system-wide? I'd assume that SIP would get in the way, but if that weren't an issue, it probably wouldn't require much more than an (admittedly somewhat sketchy) daemon that would override the system default of any app with whatever the desired theme is.

Once again, this is all assuming that Apple SIP is 100% okay with an app basically arbitrarily controlling portions of the OS....

**Comment by nfgrilo** [comment]
No, that's not possible - SIP doesn't allow code injection into other apps anymore.
