### ISSUE TITLE
Objective-C with precompiled framework

### ISSUE THREAD

**Issue by aonez** [luckymarmot/ThemeKit#6]
I've added the release framework to my project, included the import as this:

```objective-c
@import ThemeKit;
```

Saw on #5 that you've mentioned `macOSThemeKit` but this does not appear to exists. Anyway the code compiles, so `ThemeKit` it is.

Then just included the sample code of the dark theme, but the project fails to load due to some Swift libraries not found, like `libswiftAppKit.dylib`.

Importing the ThemeKit project in my project and compiling it works, since then my app included all the Swift related frameworks. Just pointing it so Objective-c projects that do not yet use Swift code should not use the release framework, or must check all the Swift related frameworks will be added as well.

**Comment by aonez** [comment]
Looks cool though, nice framework 👍 

![untitled 5](https://user-images.githubusercontent.com/480163/29412367-a6efef1e-8358-11e7-86f1-517edd089751.png)

**Comment by nfgrilo** [comment]
Thank you again for your input!

In fact, `@import macOSThemeKit` is only for the case where the lib is pulled from CocoaPods (name was taken); for any other case `@import ThemeKit` is the way to go! Anyway, I took the chance to mention this information you just provided on the `README` file.

Thanks!
